asr:
  backend: sherpa-onnx
  ctc_model_dir: ./models/sherpa-onnx-streaming-zipformer-small-ctc-zh-int8-2025-04-01
  decoder: decoder-epoch-99-avg-1.onnx
  encoder: encoder-epoch-99-avg-1.onnx
  joiner: joiner-epoch-99-avg-1.onnx
  language: zh
  model_dir: ./models
  model_name: sherpa-onnx-streaming-zipformer-zh-14M-2023-02-23
  num_threads: 6
  sample_rate: 16000
  streaming_model: transducer
  sv_model: model.int8.onnx
  sv_model_dir: ./models/sherpa-onnx-sense-voice-zh-en-ja-ko-yue-int8-2024-07-17
  sv_tokens: tokens.txt
  tokens: tokens.txt
punctuation:
  enabled: false
  model_dir: ./models
  model_file: ''
  model_name: ''
server:
  host: 0.0.0.0
  max_connections: 1
  port: 8765
vad:
  enable_endpoint_detection: true
  rule1_min_trailing_silence: 1.2
  rule2_min_trailing_silence: 0.6
  rule3_min_utterance_length: 200.0
